[package]
name = "markdown-confluence"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_fs = "1.0.13"
clap = { version = "4.4.8", features = ["derive"] }
comrak = "0.19.0"
dotenvy = "0.15.7"
once_cell = "1.18.0"
regex = "1.10.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
walkdir = "2.4.0"
