name: "Github Action Example"
on:
  pull_request:
    branches: ["main"]

jobs:
  test_github_action:
    runs-on: ubuntu-latest
    name: Generate example space using github action
    steps:
      - uses: actions/checkout@v4
      - name: Marked Space Test
        id: marked-space-test
        uses: james-allan-lloyd/marked-space@use-docker-image-for-action
        with:
          space-directory: "example/team"
          confluence-host: ${{ vars.CONFLUENCE_HOST }}
          api-user: ${{ secrets.API_USER }}
          api-token: ${{ secrets.API_TOKEN }}
