name: "Github Action Example"
on: [push]

jobs:
  test_github_action:
    runs-on: ubuntu-latest
    name: Generate example space using github action
    steps:
      - uses: actions/checkout@v4
      - name: Marked Space Test
        id: marked-space-test
        uses: james-allan-lloyd/marked-space@action
        with:
          space-directory: "example/team"
        env:
          CONFLUENCE_HOST: ${{ vars.CONFLUENCE_HOST }}
          API_USER: ${{ secrets.API_USER }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
