name: Rust PR

on:
  pull_request:
    branches: ["main"]

jobs:
  format:
    env:
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Format
        run: cargo fmt --all -- --check
  # audit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: EmbarkStudios/cargo-deny-action@v2
  build:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/shared-build.yml
    with:
      os: ${{ matrix.os }}

  docker:
    name: "Docker"
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: build
    uses: ./.github/workflows/shared-docker-publish.yml
    secrets: inherit
    with:
      push: false
