name: Rust Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/shared-build.yml
    with:
      os: ${{ matrix.os }}

  release:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ubuntu-latest/marked-space
            windows-latest/marked-space.exe
          draft: true

  # update-version-tags:
  #   name: Update Version Tags
  #   permissions: write-all
  #   needs: release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #
  #     - name: Get version components
  #       id: get_version
  #       run: |
  #         VERSION=${GITHUB_REF#refs/tags/v}
  #         MAJOR=$(echo $VERSION | cut -d. -f1)
  #         MINOR=$(echo $VERSION | cut -d. -f2)
  #         echo "version=$VERSION" >> $GITHUB_OUTPUT
  #         echo "major=$MAJOR" >> $GITHUB_OUTPUT
  #         echo "minor=$MINOR" >> $GITHUB_OUTPUT
  #
  #     - name: Update major version tag
  #       run: |
  #         git config --global user.name "GitHub Actions"
  #         git config --global user.email "actions@github.com"
  #         git tag -f v${{ steps.get_version.outputs.major }} ${{ github.ref }}
  #         git push -f origin v${{ steps.get_version.outputs.major }}
  #
  #     - name: Update minor version tag
  #       run: |
  #         git tag -f v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} ${{ github.ref }}
  #         git push -f origin v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}
