name: Rust Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/shared-build.yml
    with:
      os: ${{ matrix.os }}
        
  release:
    permissions: write-all
    needs: build
    uses: ./.github/workflows/shared-release.yml
    with:
      prerelease: false