name: Rust Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/shared-build.yml
    with:
      os: ${{ matrix.os }}
      release: true

  docker:
    needs: build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/shared-docker-publish.yml
    secrets: inherit
    with:
      push: true

  release:
    needs: docker
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ubuntu-latest/marked-space
            windows-latest/marked-space.exe
          draft: true
